# Generated by Django 4.2 on 2023-04-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=30),
        ),
    ]
