# Generated by Django 4.2 on 2023-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0002_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=200)),
                ('ititle', models.CharField(max_length=100)),
                ('iprice', models.DecimalField(decimal_places=0, default=True, max_digits=20)),
                ('idescription', models.TextField(blank=True)),
                ('iimage', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'itemms',
            },
        ),
    ]
