# Generated by Django 4.2 on 2023-04-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0004_employee_delete_itemm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
