# Generated by Django 4.2 on 2023-04-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0005_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('imguser', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
