# Generated by Django 4.2 on 2023-04-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0006_imageuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUser',
        ),
    ]
