# Generated by Django 4.2 on 2023-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0009_imageprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.FileField(default=None, upload_to='recipe/'),
        ),
        migrations.DeleteModel(
            name='ImageProfile',
        ),
    ]
