# Generated by Django 4.2 on 2023-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0010_item_recipe_delete_imageprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recipe',
            field=models.FileField(default=True, upload_to='recipe/'),
        ),
    ]
